### ISSUE TITLE
[Feature Request] Checkbox to disable preview rotation

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#1]
It would be quite handy to have a checkbox on the lathe code page to disable the automatic rotation of the model. It can be a bit frustrating when entering code to constantly having to re rotate the model.

Love the tool though, its so useful.

**Comment by kachurovskiy** [comment]
Woo-hoo, first issue in this repository 😀 Should be fixed on https://kachurovskiy.github.io/lathecode/ now - once you rotate it manually, it won't run away anymore, hope it helps.
