### ISSUE TITLE
[Bug] Chamfers in one direction not completing properly

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#12]
Im getting an odd issue where chamfers moving from right to left dont seem to be getting cut, but chamfers moving left to right look fine

Here is a model to reproduce:

UNITS MM
STOCK D16.9 
TOOL RECT R0.2 L2 ; Using a rectangular grooving tool

L0.5 DS14.5 DE15.5
L12 D15.5
L0.5 DS15.5 DE14.5
L5 D10
L0.5 DS14.5 DE15.5
L8.5 D15.5
L0.5 DS15.5 DE14.5
L3 D10

Is it a case of the tool dimension might not be 100% accurate?
![image](https://github.com/kachurovskiy/lathecode/assets/2408274/148ed2e8-f1a1-4c8d-b8ef-ff397a2c0c6e)

**Comment by kachurovskiy** [comment]
Not sure I see the problem... Toolpath seems to match the model well?

![image](https://github.com/kachurovskiy/lathecode/assets/517919/31dd0282-ce6c-4c6f-8d15-ba6b62b7a609)

![image](https://github.com/kachurovskiy/lathecode/assets/517919/070bb3e5-f9d1-48ed-b61c-c455571bacef)

**Comment by Festivejelly** [comment]
Thats what confused me too. Preview shows fine. I thought maybe it was a backlash issue? But then all the dimensions seem to measure accurately so im a bit confused as to how it would be off. Maybe backlash isnt working well for small moves.

**Comment by kachurovskiy** [comment]
Can you post the picture of the resulting part or maybe even how the finish pass went?

**Comment by Festivejelly** [comment]
Will do, i'll take some pics when i go into my garage later.

**Comment by Festivejelly** [comment]
surface quality was really good! the finishing pass worked super well on the other chamfers just not the ones I highlighted. It kinda misses them. Maybe I need a deeper finishing pass.

**Comment by kachurovskiy** [comment]
Yes, likely a backlash issue. Consider remeasuring the backlash? Felix reported similar problem. Alternatively, adjust the lathecode to make a deeper chamfer in the areas where it's insufficient.

**Comment by Festivejelly** [comment]
Closing this as Im 100% sure this was due to backlash. Ive now properly measured what my backlash is and added that to my controller.
