### ISSUE TITLE
[Bug] Parting off before other moves

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#14]
So I made this demo shape:

UNITS MM
STOCK D16
TOOL RECT R0.2 L2 ; Using a rectangular grooving tool
FEED MOVE200 PASS100 PART10 ; speeds mm/min

L0.5 D0
L5 D10
L5 D15
L2 D0

And weirdly it generates gcode that parts off the part before it does a finishing pass. So it essentially finishes in mid air.

I guess best practice would be to leave a tiny bit of of stock to hold the part and then part it off later.

**Comment by kachurovskiy** [comment]
Thanks for reporting, should be fixed now.
