### ISSUE TITLE
[Bug] Finishing pass not being applied.

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#15]
Take this:

UNITS MM
STOCK D16
TOOL RECT R0.2 L2 ; Using a rectangular grooving tool
DEPTH CUT0.5 FINISH0.2

L0.5 D0
L5 D10
L5 D15

When I look at the generated gcode using my visualiser I can see that it only cuts as deep as 5.2mm ABS. Which means its not completing the finishing passes.

https://festivejelly.github.io/LatheGcodeVisualiser/

![image](https://github.com/kachurovskiy/lathecode/assets/2408274/8c67f417-b80f-4cac-ac08-e164288c550d)

I can see on the planner it looks like it knew it should do it:

![image](https://github.com/kachurovskiy/lathecode/assets/2408274/9d6d9d16-473b-4e54-8ab0-772868e18895)
 
 
 But it didnt generate the toolpath for it.

**Comment by kachurovskiy** [comment]
@Festivejelly I suggest to stop using `D0` suffix in your lines :) If you specify `L0.5` instead of `L0.5 D0` it works as intended.

**Comment by Festivejelly** [comment]
@kachurovskiy Ahhh I was wondering why sometimes it worked and sometimes not, thats probably why,

**Comment by Festivejelly** [comment]
Can confirm this now works as of your commit so ill close. Cheers.
