### ISSUE TITLE
Finishing pass seems to be ignored

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#17]
UNITS MM
STOCK D15.9 

TOOL RECT R0.2 L2
DEPTH CUT0.5 FINISH0.2

L0.5 D0
L0.1 DS13.3 DE13.5
L0.8 D13.5
L0.1 DS13.5 DE13.3
L6.3 D10.5
L0.1 DS10.5 DE10.3
L2 D7

As you can see no finishing pass is made. It cuts in to the end diameter of 10.5 but the finishing pass is at the same depth. So the cutting should probably going into 10.7 diameter then doing the finishing pass to take it to 10.5mm

**Comment by kachurovskiy** [comment]
Yeah, sorry, I've reverted the recent commit that caused this regression. Need to improve my test coverage.

**Comment by Festivejelly** [comment]
Seems to be fixed now thanks
