### ISSUE TITLE
[Question] Internal operations

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#2]
Hi, me again :) Does this tool support internal operations? The code seemed to elude to "inside" but the documentation is a bit sparse.

I have a few grooving tools that this would be ideal for.

Id bore the holes normally with an endmill because im lazy. But I have a 1.5mm grooving tool that I use to cut out a recess for orings inside a bore.

It would be great to be able to automate this.

**Comment by kachurovskiy** [comment]
Hi @Festivejelly, sorry, `INSIDE` directive is currently only implemented for modelling and not for GCode. More on this in #3 - thanks!
