### ISSUE TITLE
Tool shapes

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#6]
Loving the tool so far it makes designing gcode an absolute breeze.

However my best tools are actually diamond shaped, I use ground sharp inserts designed for aluminium. But they work great on everything.

But with latheCode I can only define a rectangular or circular shaped tool.

I use DCMT and CCMT normally when facing:

https://www.shop-apt.co.uk/carbide-inserts-for-turning-uni-tip/dcgt-070202-alu-ak10-carbide-inserts-for-turning-ground-and-polished-for-aluminium-uni-tip.html
https://www.shop-apt.co.uk/carbide-inserts-for-turning-uni-tip/ccgt-060202-alu-ak10-carbide-inserts-for-turning-ground-and-polished-for-aluminium-uni-tip.html

with these tools

https://www.shop-apt.co.uk/apt-93-sdjcrl-lathe-turning-tools-for-dcmt-inserts/sdjcr-1010-f07-apt-lathe-turning-tool-for-dcmt-0702-inserts.html
[-](https://www.shop-apt.co.uk/apt-95-sclcrl-lathe-turning-tools-for-ccmt-inserts/sclcr-1010-h06-apt-lathe-turning-tool-for-ccmt-0602-inserts.html)

So ideally I want to be able to specify this diamond type tool so that it doesnt generate plunge cuts.

So essentially if diamond tool is selected do lots of surfacing and facing to get to dimension

**Comment by kachurovskiy** [comment]
I've added support for angled tools, please give it a try.

**Comment by Festivejelly** [comment]
Sweet lord that was quick ill give it a test :)

**Comment by Festivejelly** [comment]
That doesnt seem to be working for me. Ive specified the tool as per the readme but it still tries to make the plunge cuts:

UNITS MM
STOCK D12

TOOL ANG R0.2 L7.75 A30 NA55

L5.5 DS0 DE4
L1.5 D8
L1 D10.5

**Comment by kachurovskiy** [comment]
Cut logic is not dependent on the tool at the moment. It's always doing face cutting to reduce part deflection. Cutting e.g. a chess figure would be much less feasible if we thin out the part first. I'm open to supporting multiple cut strategies in the future but I wonder about real-world benefits of turning vs. plunging here.

**Comment by Festivejelly** [comment]
Ah I see how you mean now. I was thinking it was going to try plunging in the middle of the stock but it wont. I think plunge cuts with a surfacing pass will absolutely be sufficient here.

**Comment by Festivejelly** [comment]
Looking at the finish that plunge cuts do it really isnt as good as turning passes.

Take a cone plunging in multiple steps then doing a very thin finishing pass yields ugly results.


![image](https://github.com/kachurovskiy/lathecode/assets/2408274/a9652bd6-e60f-4fb3-9850-b11a4d02b953)


I hand coded this Gcode and it yields a much better surface finish. Maybe we could specify the depth of a finishing pass?

![image](https://github.com/kachurovskiy/lathecode/assets/2408274/f3ef52aa-5539-4c26-9990-289a0c942ba6)

**Comment by kachurovskiy** [comment]
Can you please share the lathecode for this part?

**Comment by Festivejelly** [comment]
Sure its:

UNITS MM
STOCK D12

TOOL RECT R0.2 L3

L5.5 DS0 DE4
L1.5 D8
L1 D10.5

**Comment by kachurovskiy** [comment]
Here's the toolpath I have generated for it with my local changes for the finish pass:

![image](https://github.com/kachurovskiy/lathecode/assets/517919/fde5bab8-8667-4a7d-9bd8-81302e141af0)

Finish depth by default is 0.1mm but can be adjusted. Would that work?

**Comment by kachurovskiy** [comment]
@Festivejelly finish pass should work now, please give it a try.

**Comment by Festivejelly** [comment]
@kachurovskiy this works really well thanks for adding this. I like the animation too, nice touch! Given you've added support for the other tools and depth of cut control I think this one can be closed now. Nice work.
