### ISSUE TITLE
Bug: Clicking zoom blocks entire page

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#7]
When clicking zoom in on the generated paths sometimes it blocks the entire page and you cant scroll down to the close button. I suggest limiting the size of the container to a percentage of the screen size and have it dynamically scale. That way the button will never be outside of the viewport.

I'll have a crack at fixing it on my side when I get a chance and raise a PR but I thought I should mention it to keep track of it.

**Comment by kachurovskiy** [comment]
Thank for reporting, should be fixed now.
