### ISSUE TITLE
[Bug] Local Storage issue

### ISSUE THREAD

**Issue by Festivejelly** [kachurovskiy/lathecode#9]
At the moment when you click more under the lathe code to be able to save and load to local storage it will show anything in local storage in the list. This could include local storage from plugins and extensions etc.

To fix this I think maybe the names in local storage should be prefixed with latheCode_{name of save}

And when loading the page iterate only over those that has latheCode_ prefix.

**Comment by kachurovskiy** [comment]
Well, some folks already have stuff saved without the prefix. We can filter and only show multi-line values.

**Comment by Festivejelly** [comment]
Could we maybe iterate over existing values to determine if they are lathe code, then “fix” the ones that are

**Comment by kachurovskiy** [comment]
Yeah, but then we'd have to keep that migration code around for some unknown period of time. Hope the issue is sufficiently mitigated :) Thanks!
